using IniGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace IniGeneratorTest;

public class AllBasicTypesGeneratorTest
{
    private const string SourceClassTest = $$"""
        using IniParser;

        namespace IniGeneratorTest;

        public class AllBasicTypes
        {
            public byte ByteType { get; set; } = 0;
            public sbyte SByteType { get; set; } = 0;
            public short ShortType { get; set; } = 0;
            public ushort UShortType { get; set; } = 0;
            public int IntType { get; set; } = 0;
            public uint UIntType { get; set; } = 0;
            public long LongType { get; set; } = 0;
            public ulong ULongType { get; set; } = 0;
            public string StringType { get; set; } = string.Empty;
        }

        [IniParser.GenerateIni(typeof(AllBasicTypes))]
        public partial class AllBasicTypesSourceGenerator;
        """;

    private const string ExpectedGeneratedFileName = "AllBasicTypesSourceGenerator_AllBasicTypes.g.cs";
    private const string ExpectedGenerated = $$"""
        // <auto-generated />
        using IniParser;
        using IniParser.Model;

        namespace IniGeneratorTest;

        partial class AllBasicTypesSourceGenerator
        {

        	public static SectionData WriteAllBasicTypesSection(IniGeneratorTest.AllBasicTypes data)
        	{
        		SectionData sectionData = new SectionData("AllBasicTypes");
        		sectionData.Keys.SetKeyData(new KeyData("ByteType")
        		{
        			Value = data.ByteType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("SByteType")
        		{
        			Value = data.SByteType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("ShortType")
        		{
        			Value = data.ShortType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("UShortType")
        		{
        			Value = data.UShortType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("IntType")
        		{
        			Value = data.IntType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("UIntType")
        		{
        			Value = data.UIntType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("LongType")
        		{
        			Value = data.LongType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("ULongType")
        		{
        			Value = data.ULongType.ToString(),
        		});
        		sectionData.Keys.SetKeyData(new KeyData("StringType")
        		{
        			Value = data.StringType,
        		});
        		return sectionData;
        	}

        	public static void ReadAllBasicTypesSection(IniGeneratorTest.AllBasicTypes data, SectionData section)
        	{
        		if (section == null) return;
        		if (System.Byte.TryParse(section.Keys["ByteType"], out var parsedByteType))
        			data.ByteType = parsedByteType;
        		if (System.SByte.TryParse(section.Keys["SByteType"], out var parsedSByteType))
        			data.SByteType = parsedSByteType;
        		if (System.Int16.TryParse(section.Keys["ShortType"], out var parsedShortType))
        			data.ShortType = parsedShortType;
        		if (System.UInt16.TryParse(section.Keys["UShortType"], out var parsedUShortType))
        			data.UShortType = parsedUShortType;
        		if (System.Int32.TryParse(section.Keys["IntType"], out var parsedIntType))
        			data.IntType = parsedIntType;
        		if (System.UInt32.TryParse(section.Keys["UIntType"], out var parsedUIntType))
        			data.UIntType = parsedUIntType;
        		if (System.Int64.TryParse(section.Keys["LongType"], out var parsedLongType))
        			data.LongType = parsedLongType;
        		if (System.UInt64.TryParse(section.Keys["ULongType"], out var parsedULongType))
        			data.ULongType = parsedULongType;
        		if (section.Keys.ContainsKey("StringType"))
        			data.StringType = section.Keys["StringType"];
        	}

        	public static IniData WriteAllBasicTypesIniData(IniGeneratorTest.AllBasicTypes data)
        	{
        		IniData iniData = new IniData();
        		iniData.Sections.Add(WriteAllBasicTypesSection(data));
        		return iniData;
        	}

        	public static void ReadAllBasicTypesIniData(IniGeneratorTest.AllBasicTypes data, IniData iniData)
        	{
        		ReadAllBasicTypesSection(data, iniData.Sections.GetSectionData("AllBasicTypes"));
        	}
        }

        """;

    [Fact]
    public async Task GeneratesExpectedCode()
    {
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create([new GenerateIniAttributeGenerator(), new GenerateIniGenerator()]);

        Compilation compilation = CSharpCompilation.Create(nameof(GenerateIniGenerator),
            [CSharpSyntaxTree.ParseText(SourceClassTest)],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();

        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith(ExpectedGeneratedFileName));

        Assert.Equal(ExpectedGenerated, generatedFileSyntax.GetText().ToString(), ignoreLineEndingDifferences: true);
    }
}
