using IniGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace IniGeneratorTest;

public class DictGeneratorTest
{
    private const string SourceClassTest = $$"""
        using IniParser;

        namespace IniGeneratorTest;

        public class DictTest
        {
            public System.Collections.Generic.Dictionary<int, string> MyDict { get; set; } = new();
        }      

        [GenerateIni(typeof(DictTest))]
        public partial class DictTestSourceGenerator;
        """;

    private const string ExpectedGeneratedFileName = "DictTestSourceGenerator_DictTest.g.cs";
    private const string ExpectedGenerated = $$"""
        // <auto-generated />
        using IniParser;
        using IniParser.Model;

        namespace IniGeneratorTest;

        partial class DictTestSourceGenerator
        {
        
            public static SectionData WriteMyDictSection(System.Collections.Generic.Dictionary<System.Int32, System.String> data)
            {
        	    SectionData sectionData = new SectionData("MyDict");
        	    foreach (var item in data)
        	    {
        		    sectionData.Keys.SetKeyData(new(item.Key.ToString())
        		    {
        			    Value = item.Value,
        		    });
        	    }
        	    return sectionData;
            }

            public static void ReadMyDictSection(System.Collections.Generic.Dictionary<System.Int32, System.String> data, SectionData section)
            {
        	    if (section == null) return;
        	    foreach (var key in section.Keys)
        	    {
        		    if (!System.Int32.TryParse(key.KeyName, out var dataKey))
        			    continue;
        		    var value = key.Value;
        		    data.Add(dataKey, value);
        	    }
            }

            public static IniData WriteDictTestIniData(IniGeneratorTest.DictTest data)
            {
        	    IniData iniData = new IniData();
        	    iniData.Sections.Add(WriteMyDictSection(data.MyDict));
        	    return iniData;
            }

            public static void ReadDictTestIniData(IniGeneratorTest.DictTest data, IniData iniData)
            {
        	    ReadMyDictSection(data.MyDict, iniData.Sections.GetSectionData("MyDict"));
            }
        }

        """;

    [Fact]
    public async Task GeneratesExpectedCode()
    {
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create([new GenerateIniAttributeGenerator(), new GenerateIniGenerator()]);

        Compilation compilation = CSharpCompilation.Create(nameof(GenerateIniGenerator),
            [CSharpSyntaxTree.ParseText(SourceClassTest)],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();

        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith(ExpectedGeneratedFileName));
        Assert.Equal(ExpectedGenerated, generatedFileSyntax.GetText().ToString(), 
            ignoreLineEndingDifferences: true,
            ignoreAllWhiteSpace: true);
    }
}
