using IniGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace IniGeneratorTest;

public class ListGeneratorTest
{
    private const string SourceClassTest = $$"""
        using IniParser;

        namespace IniGeneratorTest;

        public class ListTest
        {
            public System.Collections.Generic.List<string> MyList { get; set; } = new();
        }

        [GenerateIni(typeof(ListTest))]
        public partial class ListTestSourceGenerator;
        """;

    private const string ExpectedGeneratedFileName = "ListTestSourceGenerator_ListTest.g.cs";
    private const string ExpectedGenerated = $$"""
        // <auto-generated />
        using IniParser;
        using IniParser.Model;

        namespace IniGeneratorTest;

        partial class ListTestSourceGenerator
        {
        
            public static SectionData WriteMyListSection(System.Collections.Generic.List<System.String> data)
            {
        	    SectionData sectionData = new SectionData("MyList");
        	    for (int i = 0; i < data.Count; i++)
        	    {
        		    sectionData.Keys.SetKeyData(new(i.ToString())
        		    {
        			    Value = data[i],
        		    });
        	    }
        	    return sectionData;
            }

            public static void ReadMyListSection(System.Collections.Generic.List<System.String> data, SectionData section)
            {
        	    if (section == null) return;
        	    foreach (var key in section.Keys)
        	    {
        		    data.Add(key.Value);
        	    }
            }

            public static IniData WriteListTestIniData(IniGeneratorTest.ListTest data)
            {
        	    IniData iniData = new IniData();
        	    iniData.Sections.Add(WriteMyListSection(data.MyList));
        	    return iniData;
            }

            public static void ReadListTestIniData(IniGeneratorTest.ListTest data, IniData iniData)
            {
        	    ReadMyListSection(data.MyList, iniData.Sections.GetSectionData("MyList"));
            }
        }

        """;

    [Fact]
    public async Task GeneratesExpectedCode()
    {
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create([new GenerateIniAttributeGenerator(), new GenerateIniGenerator()]);

        Compilation compilation = CSharpCompilation.Create(nameof(GenerateIniGenerator),
            [CSharpSyntaxTree.ParseText(SourceClassTest)],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();

        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith(ExpectedGeneratedFileName));

        Assert.Equal(ExpectedGenerated, generatedFileSyntax.GetText().ToString(), 
            ignoreLineEndingDifferences: true,
            ignoreAllWhiteSpace: true);
    }
}
