using IniGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace IniGeneratorTest;

public class SubClassGeneratorTest
{
    private const string SourceClassTest = $$"""
        using IniParser;

        namespace IniGeneratorTest;

        public class SubClassTest
        {
            public MyClass Class { get; set; } = new();
            [GenerateIniSection("ExtraClassName")]
            public MyClass Class2 { get; set; } = new();
            public class MyClass
            {
                public string Name { get; set; } = string.Empty;
            }
        }

        [IniParser.GenerateIni(typeof(SubClassTest))]
        public partial class SubClassTestSourceGenerator;
        """;

    private const string ExpectedGeneratedFileName = "SubClassTestSourceGenerator_SubClassTest.g.cs";
    private const string ExpectedGenerated = $$"""
        // <auto-generated />
        using IniParser;
        using IniParser.Model;

        namespace IniGeneratorTest;

        partial class SubClassTestSourceGenerator
        {

            public static SectionData WriteClassSection(IniGeneratorTest.SubClassTest.MyClass data)
            {
        	    SectionData sectionData = new SectionData("Class");
        	    sectionData.Keys.SetKeyData(new KeyData("Name")
        	    {
        		    Value = data.Name,
        	    });
        	    return sectionData;
            }

            public static void ReadClassSection(IniGeneratorTest.SubClassTest.MyClass data, SectionData section)
            {
        	    if (section == null) return;
        	    if (section.Keys.ContainsKey("Name"))
        		    data.Name = section.Keys["Name"];
            }

            public static SectionData WriteExtraClassNameSection(IniGeneratorTest.SubClassTest.MyClass data)
            {
        	    SectionData sectionData = new SectionData("ExtraClassName");
        	    sectionData.Keys.SetKeyData(new KeyData("Name")
        	    {
        		    Value = data.Name,
        	    });
        	    return sectionData;
            }

            public static void ReadExtraClassNameSection(IniGeneratorTest.SubClassTest.MyClass data, SectionData section)
            {
        	    if (section == null) return;
        	    if (section.Keys.ContainsKey("Name"))
        		    data.Name = section.Keys["Name"];
            }

            public static IniData WriteSubClassTestIniData(IniGeneratorTest.SubClassTest data)
            {
        	    IniData iniData = new IniData();
        	    iniData.Sections.Add(WriteExtraClassNameSection(data.Class2));
        	    iniData.Sections.Add(WriteClassSection(data.Class));
        	    return iniData;
            }

            public static void ReadSubClassTestIniData(IniGeneratorTest.SubClassTest data, IniData iniData)
            {
        	    ReadExtraClassNameSection(data.Class2, iniData.Sections.GetSectionData("ExtraClassName"));
        	    ReadClassSection(data.Class, iniData.Sections.GetSectionData("Class"));
            }
        }

        """;

    [Fact]
    public async Task GeneratesExpectedCode()
    {
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create([new GenerateIniAttributeGenerator(), new GenerateIniGenerator()]);

        Compilation compilation = CSharpCompilation.Create(nameof(GenerateIniGenerator),
            [CSharpSyntaxTree.ParseText(SourceClassTest)],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();

        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith(ExpectedGeneratedFileName));

        Assert.Equal(ExpectedGenerated, generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true,
            ignoreAllWhiteSpace: true);
    }
}
