using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace IniGenerator;

[Generator(LanguageNames.CSharp)]
public class GenerateIniAttributeGenerator : IIncrementalGenerator
{
    private static readonly string AttributeSourceCode = 
        $$"""
        // <auto-generated/>

        namespace {{Consts.Namespace}}
        {

            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
            internal sealed class {{Consts.GenerateIniAttributeName}}Attribute : System.Attribute
            {
                public System.Type IniType { get; }

                public {{Consts.GenerateIniAttributeName}}Attribute(System.Type type)
                {
                    IniType = type;
                }
            }

            [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field)]
            internal sealed class {{Consts.GenerateIniSectionAttributeName}}Attribute : System.Attribute
            {
                public string SectionName { get; }
        
                public {{Consts.GenerateIniSectionAttributeName}}Attribute(string sectionName)
                {
                    SectionName = sectionName;
                }
            }

            [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field)]
            internal sealed class {{Consts.GenerateIniNameAttributeName}}Attribute : System.Attribute
            {
                public string KeyName { get; }

                public {{Consts.GenerateIniNameAttributeName}}Attribute(string keyName)
                {
                    KeyName = keyName;
                }
            }

            [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field)]
            internal sealed class {{Consts.GenerateIniCommentAttributeName}}Attribute : System.Attribute
            {
                public string Comments { get; }

                public {{Consts.GenerateIniCommentAttributeName}}Attribute(string comments)
                {
                    Comments = comments;
                }
            }

            [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field)]
            internal sealed class {{Consts.GenerateIniIgnoreAttributeName}}Attribute : System.Attribute
            {
            
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("Attributes.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));
    }
}
