using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace IniGenerator;

[Generator(LanguageNames.CSharp)]
public class GenerateIniAttributeGenerator : IIncrementalGenerator
{
    private static readonly string AttributeSourceCode = 
        $$"""
        // <auto-generated/>

        namespace {{Consts.Namespace}};

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class {{Consts.GenerateIniAttributeName}}Attribute(System.Type type) : System.Attribute
        {
            public System.Type IniType { get; } = type;
        }

        [System.AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
        internal sealed class {{Consts.GenerateIniSectionAttributeName}}Attribute(string sectionName) : System.Attribute
        {
            public string SectionName { get; } = sectionName;
        }

        [System.AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
        internal sealed class {{Consts.GenerateIniNameAttributeName}}Attribute(string keyName) : System.Attribute
        {
            public string KeyName { get; } = keyName;
        }

        [System.AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
        internal sealed class {{Consts.GenerateIniCommentAttributeName}}Attribute(string comments) : System.Attribute
        {
            public string Comments { get; } = comments;
        }

        [System.AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
        internal sealed class {{Consts.GenerateIniIgnoreAttributeName}}Attribute : System.Attribute;
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("Attributes.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)));
    }
}
